# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='invalid description'),
        ),
        migrations.AddField(
            model_name='course',
            name='ends_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='started_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=255),
        ),
    ]
